# Generated by Django 5.1.4 on 2025-01-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_applanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompetence',
            name='language',
            field=models.ForeignKey(default=1, help_text='The language this entry applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_language', to='common.applanguage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='language',
            field=models.ForeignKey(default=1, help_text='The language this entry applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_language', to='common.applanguage'),
            preserve_default=False,
        ),
    ]
