# Generated by Django 5.1.4 on 2025-01-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_aboutcompetence_language_frequentquestion_language'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='language',
            field=models.ForeignKey(default=1, help_text='The language this entry applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_language', to='common.applanguage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='language',
            field=models.ForeignKey(default=1, help_text='The language this entry applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_language', to='common.applanguage'),
            preserve_default=False,
        ),
    ]
