# Generated by Django 5.1.4 on 2025-01-08 14:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_language_servicepackage_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='servicepackage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddvtmmwk5/image/upload/v1234567890/placeholder.png', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddvtmmwk5/image/upload/v1234567890/placeholder.png', max_length=255, verbose_name='image'),
        ),
    ]
